import { Roboto } from "next/font/google";
import "./globals.css";
import s from "@/components/layout/Story.module.sass";
import {Header} from "@/components/layout";

const roboto = Roboto({ subsets: ["latin"], weight: ['400','500','700'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{overflowX: 'hidden'}} className={roboto.className}>
      <div className={'container'}>
          <Header/>
      </div>
      {children}
      <footer className={s.copyright}>
        © 2023 All rights reserved
      </footer>
      </body>
    </html>
  );
}
